config/routes.rb
Rails.application.routes.draw do
  
 get 'tags/:tag', to: 'upload#view', as: :tag

  resources :upload do
    post 'create_image'
    get 'view', on: :collection
  end

  devise_for :users
  authenticated :user do
    root :to => "upload#new", :as => "authenticated_root"
  end

  root 'gallery#index'

end

app/models/albumb.rb
class Albumb < ActiveRecord::Base
  belongs_to :user
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  def self.search(search)
    if search
      where('name LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%")
    else
      all
    end
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :albumb
  has_attached_file :avatar, :styles => { :medium => "500x500>", :thumb => ["500x600>", :jpg] }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  acts_as_taggable
  
  
  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :albumbs, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  
  def index
    
    
    @i=1
    if Image.limit(20).count<1
      render text: "something going wrong"
    else
      @images=Image.limit(8)
      
    end
    
    
    
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  layout "profile" 
  before_action :authenticate_user!
  def new    
    @user_action="My Albums"
    @albumb=Albumb.new
    @albumb.images.build
    if params[:search]
         @all_albumb = Albumb.search(params[:search])
         @images= Image.search(params[:search])
    else           
       
         @all_albumb=Albumb.all
          
    end
  end
  def create
    @albumb=Albumb.new(albumb_params)
    @albumb.user_id=current_user.id
    @albumb.save  
    redirect_to new_upload_path      
  end
  
 def show
    @user_action="Album images"   
    @albumb=Albumb.find(params[:id])
    @images=@albumb.images
    @image=Image.new 
      
 end
  
  def create_image
    
     @image=Image.new(image_params)
     
     @image.albumb_id=params[:upload_id]
     
     @image.save 
     redirect_to upload_path(params[:upload_id]) 
  
  end
 
  def destroy
    @album= Albumb.find(params[:id])
    @album.destroy
    redirect_to new_upload_path
    
  end
  
  def view
    if params[:tag]
    @images = Image.tagged_with(params[:tag])
    else
      render text: "something going wrong"
    end
    
  end
  
  private
  def albumb_params
    params.require(:albumb).permit(:name, :description, images_attributes: [:name, :avatar, :tag_list])
  end
  def image_params
    params.require(:image).permit(:name, :avatar, :tag_list)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/gallery/_error_page.html.erb
		
		<div class="col-md-3">
		
	
			<h2> Add New Album</h2>
				<%= bootstrap_form_for @albumb, url: upload_index_path, :html => { :multipart => true } do |f| %>
				<p>
    
   					 <%= f.text_field :name %>
  				</p>
 
				 <p>
    
   					 <%= f.text_area :description %>
  				</p>
  
  
  						<%= f.fields_for :images, :html => { :multipart => true } do |image| %>
  		
  		
  							<%= image.text_field :name%><br/>
  		
    						<%= image.file_field :avatar %><br>
    	
    	
    						<%= image.text_field :tag_list %><br />
  						<% end %>
  
 
  					<p>
    				<%= f.submit %>
  					</p>
 				<% end%>
 		</div>
 

app/views/gallery/index.html.erb
<div class="container-fluid">
<%k=0%>
<%for i in 0..2%>
	
	<div class="row margin-bottom-3">
		<% for j in 0..3 %>
	
			<div class="col-md-3 ">
				<div class="img-box-hieght">
					<div>
						<%= image_tag(@images[k].avatar.url(:thumb),class: "img-responsive")%>
						
					</div>
					<hr class="alt">
					<div><p>Name: 
					<%= @images[k].name%>
					</p>	
					</div>
					<div><p>Albumb: 
					<%= @images[k].albumb.name%>
					</p>	
					</div>
					<div><p>Tags: 
					
						<%= raw @images[k].tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %>
					
						</p>	
					</div>
				</div>
			</div>
		<%end%>
		<% k= k+1 %>
	</div>
	
	<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sharegallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="back">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ShareGallery", root_path, class: "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li class="divider-vertical"></li>
        <li><a href="#">about</a></li>
        <li class="divider-vertical"></li>
 		<li>     
      
      
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
          
        </div>
        
      </form>
      </li>
      
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li class="divider-vertical"></li>
        <li><%= link_to 'Sign in', user_session_path  %></li>
        <li class="divider-vertical"></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <li class="divider-vertical"></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>
<div class="container-fluid footer">
	
	<hr class="alt">
	<div class="col-md-9">© 2014 Share Gallery. All right reserved.</div>
	<div class="col-md-2 "><div class="margin-left-20">Terms of services</div></div>
	<div class="col-md-1">Privacy</div>
</div>
</body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sharegallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="back">
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ShareGallery</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li class="divider-vertical"></li>
        <li><a href="#">about</a></li>
        <li class="divider-vertical"></li>
 	 </ul>
       
      <%= form_tag new_upload_path, method: :get, class: "navbar-form navbar-left" do %>
        <div class="form-group">
          <%= text_field_tag :search,  params[:search] , class: "form-control" %>
        </div>
         <%= submit_tag "search", :name => nil, class: "btn btn-default" %>
      <%end%>
      <ul class="nav navbar-nav navbar-right">
      	<li class="divider-vertical"></li>
        <li><%= link_to current_user.email, root_path %></li>
        <li class="divider-vertical"></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
        <li class="divider-vertical"></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div><center><h1><%= @user_action %></h1></center></div>
<div class="container-fluid">
	
	<div class="row">
		
		
		
	
			
<%= yield %>


</div>
</div>
<div class="container-fluid footer">
	
	<hr class="alt">
	<div class="col-md-9">© 2014 Share Gallery. All right reserved.</div>
	<div class="col-md-2 "><div class="margin-left-20">Terms of services</div></div>
	<div class="col-md-1">Privacy</div>
</div>
</body>
</html>

app/views/upload/_albumb.html.erb
		
		<div class="col-md-3">
		
	
			<h2> Add New Album</h2>
				<%= bootstrap_form_for @albumb, url: upload_index_path, :html => { :multipart => true } do |f| %>
				<p>
    
   					 <%= f.text_field :name %>
  				</p>
 
				 <p>
    
   					 <%= f.text_area :description %>
  				</p>
  
  
  						<%= f.fields_for :images, :html => { :multipart => true } do |image| %>
  		
  		
  							<%= image.text_field :name%><br/>
  		
    						<%= image.file_field :avatar %><br>
    	
    	
    						<%= image.text_field :tag_list %><br />
  						<% end %>
  
 
  					<p>
    				<%= f.submit %>
  					</p>
 				<% end%>
 		</div>
 

app/views/upload/_error_page.html.erb
		
		<div class="col-md-3">
		
	
			<h2> Add New Album</h2>
				<%= bootstrap_form_for @albumb, url: upload_index_path, :html => { :multipart => true } do |f| %>
				<p>
    
   					 <%= f.text_field :name %>
  				</p>
 
				 <p>
    
   					 <%= f.text_area :description %>
  				</p>
  
  
  						<%= f.fields_for :images, :html => { :multipart => true } do |image| %>
  		
  		
  							<%= image.text_field :name%><br/>
  		
    						<%= image.file_field :avatar %><br>
    	
    	
    						<%= image.text_field :tag_list %><br />
  						<% end %>
  
 
  					<p>
    				<%= f.submit %>
  					</p>
 				<% end%>
 		</div>
 

app/views/upload/_images.html.erb
		<div class="col-md-3">
		
	
			<h2> Add image in albumb</h2>
				<%= bootstrap_form_for @image, url: upload_create_image_path(@albumb)  do |image| %>
				
  
  						
  		
  		
  							<%= image.text_field :name%><br/>
  		
    						<%= image.file_field :avatar %><br>
    	
    	
    						<%= image.text_field :tag_list %><br />
    						
    				
 
  					<p>
    				<%= image.submit %>
  					</p>
 				<% end%>
 		</div>

app/views/upload/new.html.erb
<%= render 'albumb'%>
		
		<% @all_albumb.each do |albumb| %>
		<div class="col-md-3  margin-bottom-3">
			<div class="img-box-hieght">
				<div>
					<%= link_to image_tag(albumb.images.first.avatar.url(:thumb),class: "img-responsive"), upload_path(albumb)%>			
						
				</div>
				<hr class="alt">
				<div><p>Name: 
					<%= albumb.name%>
					</p>	
				</div>
				<div><p>Description: 
					<%= albumb.description%>
					</p>	
				</div>
				<div><p> 
					<%= link_to "Delete Album", upload_path(albumb), method: :delete %>
					</p>	
				</div>
			</div>
		</div>
		<%end%>
	<% if defined? @images %>
		
		<% @images.each do |image| %>
		<div class="col-md-3  margin-bottom-3">
			<div class="img-box-hieght">
				<div>
					<%= image_tag(image.avatar.url(:thumb),class: "img-responsive")%>			
						
				</div>
				<hr class="alt">
				<div><p>Name: 
					<%= image.name%>
					</p>	
				</div>
				<div><p>Tags: 
					
					<%= raw image.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %>
					</p>	
				</div>
				
			</div>
		</div>
		<%end%>
		<%end%>

	

app/views/upload/show.html.erb
<%= render 'images' %>
		
		<% @images.each do |image| %>
		<div class="col-md-3  margin-bottom-3">
			<div class="img-box-hieght">
				<div>
					<%= image_tag(image.avatar.url(:thumb),class: "img-responsive")%>			
						
				</div>
				<hr class="alt">
				<div><p>Name: 
					<%= image.name%>
					</p>	
				</div>
				<div><p>Tags: 
					
					<%= raw image.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %>
					</p>	
				</div>
				
			</div>
		</div>
		<%end%>

	

app/views/upload/view.html.erb
<div class="container-fluid">
<div class="row margin-bottom-3">
<%for image in @images %>
	
	
	
			<div class="col-md-3 ">
				<div class="img-box-hieght">
					<div>
						<%= image_tag(image.avatar.url(:thumb),class: "img-responsive")%>
						
					</div>
					<hr class="alt">
					<div><p>Name: 
					<%= image.name%>
					</p>	
					</div>
					<div><p>Albumb: 
					<%= image.albumb.name%>
					</p>	
					</div>
					<div><p>Tags: 
					
						<%= raw image.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %>
					
						</p>	
					</div>
				</div>
			</div>
		
		<%end%>
	</div>
	
	
</div>